services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - frontend
